//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prilozenie.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KrossEntities2 : DbContext
    {
        public KrossEntities2()
            : base("name=KrossEntities2")
        {
        }


        public static KrossEntities2 _context;

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static KrossEntities2 GetContext()
        {
            if (_context == null)
                _context = new KrossEntities2();
            return _context;
        }

        public virtual DbSet<CableType> CableType { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Kross> Kross { get; set; }
        public virtual DbSet<Linear> Linear { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Visit> Visit { get; set; }
    }
}
