//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prilozenie.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Id_Visit { get; set; }
        public Nullable<System.DateTime> DateToVisit { get; set; }
        public Nullable<int> Id_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
